name: Task
description: Task
labels: []
assignees: []
title: "[Task] <short description>"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the task
      placeholder: "Describe the task"
    validations:
      required: true

# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

