# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

FROM debian:trixie-slim

WORKDIR /app

RUN apt update && apt-get -y install\
        gstreamer1.0-plugins-good\
        gstreamer1.0-x \
        patchelf && rm -rf /var/lib/apt/lists/*

COPY build/Linux-Clang-Release/lib/*.so* /app/
COPY build/Linux-Clang-Release/lib/internal/*.so* /app/
COPY build/Linux-Clang-Release/lib/tests/data/*.json /app/
COPY build/Linux-Clang-Release/tools/mxl-gst/mxl-gst-testsrc /app/

RUN patchelf --set-rpath /app mxl-gst-testsrc

CMD ["/app/mxl-gst-testsrc", "-d", "/domain", "-v", "/app/v210_flow.json", "-a", "/app/audio_flow.json"]
