# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

FROM debian:trixie-slim

WORKDIR /app

RUN apt update && apt-get -y install\
        procps \
        patchelf && rm -rf /var/lib/apt/lists/*

COPY build/Linux-Clang-Release/lib/*.so* /app/
COPY build/Linux-Clang-Release/tools/mxl-info/mxl-info /app/

RUN patchelf --set-rpath /app mxl-info

CMD["sh", "-c", "while true; do /app/mxl-info -d /domain -l || true; sleep 2; done"]
