FROM debian:trixie-slim

WORKDIR /app

RUN apt update && apt-get -y install\
        gstreamer1.0-plugins-good\
        gstreamer1.0-x \
        patchelf && rm -rf /var/lib/apt/lists/*

COPY build/Linux-Clang-Release/lib/*.so* /app/
COPY build/Linux-Clang-Release/lib/tests/data/*.json /app/
COPY build/Linux-Clang-Release/tools/mxl-gst/mxl-gst-videotestsrc /app/

RUN patchelf --set-rpath /app mxl-gst-videotestsrc

CMD ["/app/mxl-gst-videotestsrc", "-d", "/domain", "-f", "/app/v210_flow.json"]
